### ISSUE TITLE
docker-compose.yml not working

### ISSUE THREAD

**Issue by robsonpeixoto** [HubSpot/Singularity#1107]
When run a container with `--net=host` the `InetAddress addr = InetAddress.getLocalHost();` fail.

Reference: https://github.com/docker/docker/issues/6027
```
~/src/Singularity git:(master)
❯ docker-compose up -d                                                                                                                                                          09:32
Starting singularity_baragonservice_1
Starting singularity_zk_1
Starting singularity_baragonagent_1
Starting singularity_master_1
Starting singularity_slave_1
Starting singularity_scheduler_1

~/src/Singularity git:(master)
❯ docker-compose logs -f baragonservice                                                                                                                                      1s 207ms
Attaching to singularity_baragonservice_1
baragonservice_1  | INFO  [2016-06-22 12:04:30,365] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: assets for path /static/*
baragonservice_1  | INFO  [2016-06-22 12:04:30,442] com.hubspot.dropwizard.guice.AutoConfig: Added injectableHealthCheck: class com.hubspot.baragon.service.healthcheck.ZooKeeperHealthcheck
baragonservice_1  | INFO  [2016-06-22 12:04:30,445] com.hubspot.dropwizard.guice.AutoConfig: Added provider class: class com.hubspot.baragon.service.exceptions.NotifyingExceptionMapper
baragonservice_1  | INFO  [2016-06-22 12:04:30,449] com.hubspot.dropwizard.guice.AutoConfig: Added resource class: class com.hubspot.baragon.service.resources.ElbResource
baragonservice_1  | INFO  [2016-06-22 12:04:30,449] com.hubspot.dropwizard.guice.AutoConfig: Added resource class: class com.hubspot.baragon.service.resources.AgentCheckinResource
baragonservice_1  | INFO  [2016-06-22 12:04:30,449] com.hubspot.dropwizard.guice.AutoConfig: Added resource class: class com.hubspot.baragon.service.resources.StatusResource
baragonservice_1  | INFO  [2016-06-22 12:04:30,449] com.hubspot.dropwizard.guice.AutoConfig: Added resource class: class com.hubspot.baragon.service.resources.LoadBalancerResource
baragonservice_1  | INFO  [2016-06-22 12:04:30,449] com.hubspot.dropwizard.guice.AutoConfig: Added resource class: class com.hubspot.baragon.service.resources.RequestResource
baragonservice_1  | INFO  [2016-06-22 12:04:30,450] com.hubspot.dropwizard.guice.AutoConfig: Added resource class: class com.hubspot.baragon.service.resources.MetricsResource
baragonservice_1  | INFO  [2016-06-22 12:04:30,450] com.hubspot.dropwizard.guice.AutoConfig: Added resource class: class com.hubspot.baragon.service.resources.UIResource
baragonservice_1  | INFO  [2016-06-22 12:04:30,450] com.hubspot.dropwizard.guice.AutoConfig: Added resource class: class com.hubspot.baragon.service.resources.WorkerResource
baragonservice_1  | INFO  [2016-06-22 12:04:30,450] com.hubspot.dropwizard.guice.AutoConfig: Added resource class: class com.hubspot.baragon.service.resources.StateResource
baragonservice_1  | INFO  [2016-06-22 12:04:30,450] com.hubspot.dropwizard.guice.AutoConfig: Added resource class: class com.hubspot.baragon.service.resources.AuthResource
baragonservice_1  | INFO  [2016-06-22 12:04:30,454] com.hubspot.dropwizard.guice.AutoConfig: Added managed: class com.hubspot.baragon.service.managed.BaragonExceptionNotifierManaged
baragonservice_1  | Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:
baragonservice_1  |
baragonservice_1  | 1) Error in custom provider, java.lang.RuntimeException: No local hostname found, unable to start without functioning local networking (or configured hostname)
baragonservice_1  |   at com.hubspot.baragon.service.BaragonServiceModule.providesLocalHostnameProperty(BaragonServiceModule.java:145)
baragonservice_1  |   while locating java.lang.String annotated with @com.google.inject.name.Named(value=baragon.service.local.hostname)
baragonservice_1  |     for parameter 2 at com.hubspot.baragon.service.managed.BaragonGraphiteReporterManaged.<init>(BaragonGraphiteReporterManaged.java:37)
baragonservice_1  |   at com.hubspot.baragon.service.managed.BaragonGraphiteReporterManaged.class(BaragonGraphiteReporterManaged.java:27)
baragonservice_1  |   while locating com.hubspot.baragon.service.managed.BaragonGraphiteReporterManaged
baragonservice_1  |
baragonservice_1  | 1 error
baragonservice_1  | 	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
baragonservice_1  | 	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
baragonservice_1  | 	at com.hubspot.dropwizard.guice.AutoConfig.addManaged(AutoConfig.java:61)
baragonservice_1  | 	at com.hubspot.dropwizard.guice.AutoConfig.run(AutoConfig.java:50)
baragonservice_1  | 	at com.hubspot.dropwizard.guice.GuiceBundle.run(GuiceBundle.java:139)
baragonservice_1  | 	at com.hubspot.dropwizard.guice.GuiceBundle.run(GuiceBundle.java:28)
baragonservice_1  | 	at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:176)
baragonservice_1  | 	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:41)
baragonservice_1  | 	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76)
baragonservice_1  | 	at io.dropwizard.cli.Cli.run(Cli.java:70)
baragonservice_1  | 	at io.dropwizard.Application.run(Application.java:72)
baragonservice_1  | 	at com.hubspot.baragon.service.BaragonService.main(BaragonService.java:38)
baragonservice_1  | Caused by: java.lang.RuntimeException: No local hostname found, unable to start without functioning local networking (or configured hostname)
baragonservice_1  | 	at com.hubspot.baragon.service.BaragonServiceModule.providesLocalHostnameProperty(BaragonServiceModule.java:154)
baragonservice_1  | 	at com.hubspot.baragon.service.BaragonServiceModule$$FastClassByGuice$$f7a2457c.invoke(<generated>)
baragonservice_1  | 	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:272)
baragonservice_1  | 	at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:172)
baragonservice_1  | 	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
baragonservice_1  | 	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
baragonservice_1  | 	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
baragonservice_1  | 	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
baragonservice_1  | 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
baragonservice_1  | 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
baragonservice_1  | 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
baragonservice_1  | 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
baragonservice_1  | 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
baragonservice_1  | 	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
baragonservice_1  | 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
baragonservice_1  | 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
baragonservice_1  | 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
baragonservice_1  | 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
baragonservice_1  | 	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
baragonservice_1  | 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
baragonservice_1  | 	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
baragonservice_1  | 	... 11 more
baragonservice_1  | Caused by: java.net.UnknownHostException: moby: moby: unknown error
baragonservice_1  | 	at java.net.InetAddress.getLocalHost(InetAddress.java:1484)
baragonservice_1  | 	at com.hubspot.baragon.service.BaragonServiceModule.providesLocalHostnameProperty(BaragonServiceModule.java:150)
baragonservice_1  | 	... 31 more
baragonservice_1  | Caused by: java.net.UnknownHostException: moby: unknown error
baragonservice_1  | 	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
baragonservice_1  | 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:907)
baragonservice_1  | 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1302)
baragonservice_1  | 	at java.net.InetAddress.getLocalHost(InetAddress.java:1479)
baragonservice_1  | 	... 32 more
baragonservice_1  | INFO  [2016-06-22 12:32:59,192] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: assets for path /static/*
baragonservice_1  | INFO  [2016-06-22 12:32:59,292] com.hubspot.dropwizard.guice.AutoConfig: Added injectableHealthCheck: class com.hubspot.baragon.service.healthcheck.ZooKeeperHealthcheck
baragonservice_1  | INFO  [2016-06-22 12:32:59,293] com.hubspot.dropwizard.guice.AutoConfig: Added provider class: class com.hubspot.baragon.service.exceptions.NotifyingExceptionMapper
baragonservice_1  | INFO  [2016-06-22 12:32:59,297] com.hubspot.dropwizard.guice.AutoConfig: Added resource class: class com.hubspot.baragon.service.resources.ElbResource
baragonservice_1  | INFO  [2016-06-22 12:32:59,309] com.hubspot.dropwizard.guice.AutoConfig: Added resource class: class com.hubspot.baragon.service.resources.AgentCheckinResource
baragonservice_1  | INFO  [2016-06-22 12:32:59,309] com.hubspot.dropwizard.guice.AutoConfig: Added resource class: class com.hubspot.baragon.service.resources.StatusResource
baragonservice_1  | INFO  [2016-06-22 12:32:59,309] com.hubspot.dropwizard.guice.AutoConfig: Added resource class: class com.hubspot.baragon.service.resources.LoadBalancerResource
baragonservice_1  | INFO  [2016-06-22 12:32:59,309] com.hubspot.dropwizard.guice.AutoConfig: Added resource class: class com.hubspot.baragon.service.resources.RequestResource
baragonservice_1  | INFO  [2016-06-22 12:32:59,309] com.hubspot.dropwizard.guice.AutoConfig: Added resource class: class com.hubspot.baragon.service.resources.MetricsResource
baragonservice_1  | INFO  [2016-06-22 12:32:59,309] com.hubspot.dropwizard.guice.AutoConfig: Added resource class: class com.hubspot.baragon.service.resources.UIResource
baragonservice_1  | INFO  [2016-06-22 12:32:59,309] com.hubspot.dropwizard.guice.AutoConfig: Added resource class: class com.hubspot.baragon.service.resources.WorkerResource
baragonservice_1  | INFO  [2016-06-22 12:32:59,309] com.hubspot.dropwizard.guice.AutoConfig: Added resource class: class com.hubspot.baragon.service.resources.StateResource
baragonservice_1  | INFO  [2016-06-22 12:32:59,309] com.hubspot.dropwizard.guice.AutoConfig: Added resource class: class com.hubspot.baragon.service.resources.AuthResource
baragonservice_1  | INFO  [2016-06-22 12:32:59,326] com.hubspot.dropwizard.guice.AutoConfig: Added managed: class com.hubspot.baragon.service.managed.BaragonExceptionNotifierManaged
baragonservice_1  | Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:
baragonservice_1  |
baragonservice_1  | 1) Error in custom provider, java.lang.RuntimeException: No local hostname found, unable to start without functioning local networking (or configured hostname)
baragonservice_1  |   at com.hubspot.baragon.service.BaragonServiceModule.providesLocalHostnameProperty(BaragonServiceModule.java:145)
baragonservice_1  |   while locating java.lang.String annotated with @com.google.inject.name.Named(value=baragon.service.local.hostname)
baragonservice_1  |     for parameter 2 at com.hubspot.baragon.service.managed.BaragonGraphiteReporterManaged.<init>(BaragonGraphiteReporterManaged.java:37)
baragonservice_1  |   at com.hubspot.baragon.service.managed.BaragonGraphiteReporterManaged.class(BaragonGraphiteReporterManaged.java:27)
baragonservice_1  |   while locating com.hubspot.baragon.service.managed.BaragonGraphiteReporterManaged
baragonservice_1  |
baragonservice_1  | 1 error
baragonservice_1  | 	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
baragonservice_1  | 	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
baragonservice_1  | 	at com.hubspot.dropwizard.guice.AutoConfig.addManaged(AutoConfig.java:61)
baragonservice_1  | 	at com.hubspot.dropwizard.guice.AutoConfig.run(AutoConfig.java:50)
baragonservice_1  | 	at com.hubspot.dropwizard.guice.GuiceBundle.run(GuiceBundle.java:139)
baragonservice_1  | 	at com.hubspot.dropwizard.guice.GuiceBundle.run(GuiceBundle.java:28)
baragonservice_1  | 	at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:176)
baragonservice_1  | 	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:41)
baragonservice_1  | 	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76)
baragonservice_1  | 	at io.dropwizard.cli.Cli.run(Cli.java:70)
baragonservice_1  | 	at io.dropwizard.Application.run(Application.java:72)
baragonservice_1  | 	at com.hubspot.baragon.service.BaragonService.main(BaragonService.java:38)
baragonservice_1  | Caused by: java.lang.RuntimeException: No local hostname found, unable to start without functioning local networking (or configured hostname)
baragonservice_1  | 	at com.hubspot.baragon.service.BaragonServiceModule.providesLocalHostnameProperty(BaragonServiceModule.java:154)
baragonservice_1  | 	at com.hubspot.baragon.service.BaragonServiceModule$$FastClassByGuice$$f7a2457c.invoke(<generated>)
baragonservice_1  | 	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:272)
baragonservice_1  | 	at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:172)
baragonservice_1  | 	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
baragonservice_1  | 	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
baragonservice_1  | 	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
baragonservice_1  | 	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
baragonservice_1  | 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
baragonservice_1  | 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
baragonservice_1  | 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
baragonservice_1  | 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
baragonservice_1  | 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
baragonservice_1  | 	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
baragonservice_1  | 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
baragonservice_1  | 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
baragonservice_1  | 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
baragonservice_1  | 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
baragonservice_1  | 	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
baragonservice_1  | 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
baragonservice_1  | 	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
baragonservice_1  | 	... 11 more
baragonservice_1  | Caused by: java.net.UnknownHostException: moby: moby: unknown error
baragonservice_1  | 	at java.net.InetAddress.getLocalHost(InetAddress.java:1484)
baragonservice_1  | 	at com.hubspot.baragon.service.BaragonServiceModule.providesLocalHostnameProperty(BaragonServiceModule.java:150)
baragonservice_1  | 	... 31 more
baragonservice_1  | Caused by: java.net.UnknownHostException: moby: unknown error
baragonservice_1  | 	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
baragonservice_1  | 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:907)
baragonservice_1  | 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1302)
baragonservice_1  | 	at java.net.InetAddress.getLocalHost(InetAddress.java:1479)
baragonservice_1  | 	... 32 more
singularity_baragonservice_1 exited with code 1
```

**Comment by ssalinas** [comment]
@robsonpeixoto Thanks for reporting this. Interestingly it's working in my local setup, but I think I can add in some optional environment variables in the Baragon/Singularity images to set that config property. It will key off of those then instead of doing the lookup. I'll close this when the new images are up

**Comment by ssalinas** [comment]
Images for Singularity 0.8.0 and 0.9.0-SNAPSHOT and Baragon 0.4.0 and 0.5.0-SNAPSHOT will now look to the (BARAGON|SINGULARITY)_HOSTNAME var for that config property, and will set it automatically from the content of DOCKER_HOST if it is not already specified. This should take care of the issue you were seeing. If you still run into problems, feel free to reopen this issue

**Comment by robsonpeixoto** [comment]
Now I got this error
```
❯ docker-compose logs scheduler                                                                                                                                                 547ms
Attaching to singularity_scheduler_1
scheduler_1       | /etc/singularity/start.sh: line 26: syntax error near unexpected token `('
scheduler_1       | /etc/singularity/start.sh: line 26: `[[ ! ${SINGULARITY_HOSTNAME:-} ]] || args+= ( -Ddw.hostname="${SINGULARITY_HOSTNAME}" )'
```

**Comment by ssalinas** [comment]
Just pushed new images, sorry about that one

**Comment by robsonpeixoto** [comment]
@ssalinas more erros. 

```
❯ docker-compose logs scheduler                                                                                                                                                 569ms
Attaching to singularity_scheduler_1
scheduler_1       | Running: java -Ddw.server.connector.port=7099 -Ddw.loadBalancerUri=http://localhost:8080/baragon/v2/request -Xmx512m -Djava.net.preferIPv4Stack=true -Ddw.mesos.master=zk://localhost:2181/mesos -Ddw.zookeeper.quorum=localhost:2181 -Ddw.zookeeper.zkNamespace=singularity -Ddw.ui.baseUrl=http://localhost:7099/singularity -Ddw.hostname=localhost -jar /SingularityService.jar server /etc/singularity/singularity.yaml
scheduler_1       | INFO  [2016-06-22 18:39:52,471] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: assets for path /static/*
scheduler_1       | INFO  [2016-06-22 18:39:52,645] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: api-docs for path /api-docs/*
scheduler_1       | Failed to obtain the IP address for 'moby'; the DNS service may not be able to resolve it: Name or service not known
```

**Comment by ssalinas** [comment]
Is `moby` the hostname for the vm where you are running docker? For your mesos master? Also, is that hostname vaild if you try to resolve it by any other method within the container?

**Comment by robsonpeixoto** [comment]
@ssalinas I just run the `docker-compose up` without change the `docker-compose.yml`

**Comment by ssalinas** [comment]
Ok, it seems it is most likely a difference in your local docker setup. How are you running docker? (boot2docker?, docker-machine?) and what is `DOCKER_HOST` set to for you?

As an alternative, you can always add SINGULARITY_HOSTNAME=localhost to the compose file and that should get it going if you are just trying to test things out

**Comment by robsonpeixoto** [comment]
I'm using Docker Beta Version 1.12.0-rc2-beta16 (build: 9493).
As I'm using the Docker Beta, my `DOCKER_HOST` is empty.

About the `SINGULARITY_HOSTNAME`, I put on `scheduler` session.
After that, I did: `docker-compose rm -f` and `docker-compose up`:

And I got the same error:
```
Attaching to singularity_scheduler_1
scheduler_1       | Running: java -Ddw.server.connector.port=7099 -Ddw.loadBalancerUri=http://localhost:8080/baragon/v2/request -Xmx512m -Djava.net.preferIPv4Stack=true -Ddw.mesos.master=zk://localhost:2181/mesos -Ddw.zookeeper.quorum=localhost:2181 -Ddw.zookeeper.zkNamespace=singularity -Ddw.ui.baseUrl=http://localhost:7099/singularity -Ddw.hostname=localhost -jar /SingularityService.jar server /etc/singularity/singularity.yaml
scheduler_1       | INFO  [2016-06-23 03:20:20,758] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: assets for path /static/*
scheduler_1       | INFO  [2016-06-23 03:20:20,894] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: api-docs for path /api-docs/*
scheduler_1       | Failed to obtain the IP address for 'moby'; the DNS service may not be able to resolve it: Name or service not known
```

**Comment by ssalinas** [comment]
We don't quite have the bandwidth to test out beta versions of docker, if you send me your email though, I'd be happy to invite you to our slack channel to chat easier/more quickly. Might be some other folks there that could help as well.

**Comment by robsonpeixoto** [comment]
@ssalinas robsonpeixoto@gmail.com
