### ISSUE TITLE
SingularityDeployPoller IllegalArgumentException: durationMillis must not be negative

### ISSUE THREAD

**Issue by stevenschlansker** [HubSpot/Singularity#1174]
Singularity 0.6.2 crashed with:

```
DEBUG [2016-07-27 20:48:55,840] com.hubspot.singularity.scheduler.SingularityDeployChecker: Checking a deploy SingularityPendingDeploy [deployMarker=SingularityDeployMarker [requestId=mobile-web-frontend, deployId=teamcity.2016.07.27T20.48.55, timestamp=1469652535842, user=Optional.absent(), message=Optional.a
bsent()], lastLoadBalancerUpdate=Optional.absent(), currentDeployState=WAITING, deployProgress=Optional.of(SingularityIncrementalDeployProgress{targetActiveInstances=4, deployInstanceCountPerStep=4, deployStepWaitTimeMs=0, stepComplete=false, autoAdvanceDeploySteps=true, failedDeployTasks=[], timestamp=1469652
535842})]
ERROR [2016-07-27 20:48:55,841] com.hubspot.singularity.scheduler.SingularityLeaderOnlyPoller: Caught an exception while running SingularityDeployPoller
! java.lang.IllegalArgumentException: durationMillis must not be negative
! at org.apache.commons.lang3.Validate.inclusiveBetween(Validate.java:969) ~[singularity-0.6.2.jar:0.6.2]
! at org.apache.commons.lang3.time.DurationFormatUtils.formatDuration(DurationFormatUtils.java:131) ~[singularity-0.6.2.jar:0.6.2]
! at org.apache.commons.lang3.time.DurationFormatUtils.formatDuration(DurationFormatUtils.java:114) ~[singularity-0.6.2.jar:0.6.2]
! at org.apache.commons.lang3.time.DurationFormatUtils.formatDurationHMS(DurationFormatUtils.java:83) ~[singularity-0.6.2.jar:0.6.2]
! at com.hubspot.singularity.scheduler.SingularityDeployChecker.isDeployOverdue(SingularityDeployChecker.java:310) ~[singularity-0.6.2.jar:0.6.2]
! at com.hubspot.singularity.scheduler.SingularityDeployChecker.checkDeployProgress(SingularityDeployChecker.java:466) ~[singularity-0.6.2.jar:0.6.2]
! at com.hubspot.singularity.scheduler.SingularityDeployChecker.getDeployResult(SingularityDeployChecker.java:431) ~[singularity-0.6.2.jar:0.6.2]
! at com.hubspot.singularity.scheduler.SingularityDeployChecker.checkDeploy(SingularityDeployChecker.java:150) ~[singularity-0.6.2.jar:0.6.2]
! at com.hubspot.singularity.scheduler.SingularityDeployChecker.checkDeploys(SingularityDeployChecker.java:98) ~[singularity-0.6.2.jar:0.6.2]
! at com.hubspot.singularity.scheduler.SingularityDeployPoller.runActionOnPoll(SingularityDeployPoller.java:35) ~[singularity-0.6.2.jar:0.6.2]
! at com.hubspot.singularity.scheduler.SingularityLeaderOnlyPoller.runActionIfLeaderAndMesosIsRunning(SingularityLeaderOnlyPoller.java:108) [singularity-0.6.2.jar:0.6.2]
! at com.hubspot.singularity.scheduler.SingularityLeaderOnlyPoller.access$000(SingularityLeaderOnlyPoller.java:24) [singularity-0.6.2.jar:0.6.2]
! at com.hubspot.singularity.scheduler.SingularityLeaderOnlyPoller$1.run(SingularityLeaderOnlyPoller.java:83) [singularity-0.6.2.jar:0.6.2]
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_72-internal]
! at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_72-internal]
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_72-internal]
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_72-internal]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72-internal]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72-internal]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72-internal]
ERROR [2016-07-27 20:48:55,850] com.hubspot.singularity.SingularityAbort: Singularity on mesos2-prod-sc is aborting due to UNRECOVERABLE_ERROR
```

Recovered after a leader election with no apparent further problems.

**Comment by ssalinas** [comment]
I haven't been able to figure out how exactly this happened tracing through the code. That value is coming from a `System.currentTimeMillis() - (other time intially set earlier in the code by System.currentTimeMillis())`, not quite sure how you got a deploy from the future in there. Can keep looking, but I don't have an immediate answer on this one

**Comment by stevenschlansker** [comment]
I've only seen it once, so it's definitely not a huge problem for us.  Just thought I'd report it for completeness's sake.  Maybe `ntp` skewed the clock or something?

**Comment by ssalinas** [comment]
It's possible that the deploy was created on a machine with a clock skewed enough that when the leader ran the poller immediately after, the time was still ahead (assuming you run multiple Singularitys for HA). Based on the log timestamps above, it was only a few ms in the negative

**Comment by stevenschlansker** [comment]
We run 3 in HA mode.

**Comment by jhaber** [comment]
`System.currentTimeMillis()` can definitely go backwards. I think `System.nanoTime()` is more reliable in that regard so we may want to update Singularity to use that where possible.
