### ISSUE TITLE
SingularityDeployChecker: Absent optional .get()

### ISSUE THREAD

**Issue by stevenschlansker** [HubSpot/Singularity#1203]
Saw a couple of these crashes with Singularity 0.9.0:

```
INFO  [2016-08-10 15:43:46,447] com.hubspot.singularity.mesos.SingularityMesosScheduler: Finished handling 19 offer(s) (00:02.061), 1 accepted, 18 declined, 0 outstanding tasks
DEBUG [2016-08-10 15:43:46,448] com.hubspot.singularity.mesos.SingularityMesosSchedulerDelegator: Handled 19 resource offers in 00:02.065
DEBUG [2016-08-10 15:43:46,451] com.hubspot.singularity.scheduler.SingularityDeployChecker: Checking a deploy SingularityPendingDeploy [deployMarker=SingularityDeployMarker [requestId=waitlist-estimator-pp, deployId=nmenne.2016.08.10T15.43.04, timestamp=1470843787103, user=Optional.absent(), message=Optional.absent()], lastLoadBalancerUpdate=Optional.absent
(), currentDeployState=WAITING, deployProgress=Optional.of(SingularityIncrementalDeployProgress{targetActiveInstances=1, deployInstanceCountPerStep=1, deployStepWaitTimeMs=0, stepComplete=false, autoAdvanceDeploySteps=true, failedDeployTasks=[], timestamp=1470843787103}), updatedRequest=Optional.absent()]
WARN  [2016-08-10 15:43:46,451] com.hubspot.singularity.scheduler.SingularityDeployChecker: Deploy MISSING request was SingularityPendingDeploy [deployMarker=SingularityDeployMarker [requestId=waitlist-estimator-pp, deployId=nmenne.2016.08.10T15.43.04, timestamp=1470843787103, user=Optional.absent(), message=Optional.absent()], lastLoadBalancerUpdate=Option
al.absent(), currentDeployState=WAITING, deployProgress=Optional.of(SingularityIncrementalDeployProgress{targetActiveInstances=1, deployInstanceCountPerStep=1, deployStepWaitTimeMs=0, stepComplete=false, autoAdvanceDeploySteps=true, failedDeployTasks=[], timestamp=1470843787103}), updatedRequest=Optional.absent()], removing deploy
ERROR [2016-08-10 15:43:46,456] com.hubspot.singularity.scheduler.SingularityLeaderOnlyPoller: Caught an exception while running SingularityDeployPoller
! java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
! at com.google.common.base.Absent.get(Absent.java:47) ~[singularity-0.9.0.jar:0.9.0]
! at com.hubspot.singularity.scheduler.SingularityDeployChecker.checkDeploy(SingularityDeployChecker.java:130) ~[singularity-0.9.0.jar:0.9.0]
! at com.hubspot.singularity.scheduler.SingularityDeployChecker.checkDeploys(SingularityDeployChecker.java:98) ~[singularity-0.9.0.jar:0.9.0]
! at com.hubspot.singularity.scheduler.SingularityDeployPoller.runActionOnPoll(SingularityDeployPoller.java:35) ~[singularity-0.9.0.jar:0.9.0]
```

**Comment by ssalinas** [comment]
This was fixed in #1184 , made it into the 0.10.0 release
