### ISSUE TITLE
Problem starting up with docker-compose on Mac

### ISSUE THREAD

**Issue by billwright** [HubSpot/Singularity#1421]
I'm running Docker for Mac 1.13.0 and when I run docker-compose up (following the instructions on the main page). I commented out the baragon stuff to make things simpler when it failed the first time. After starting up, I waited until the logs quieted down with the last lines like this:

```
master_1     | I0209 22:44:08.020092     7 hierarchical.cpp:473] Added slave 3449ccad-9dee-4360-8360-c439ec66eafb-S0 (localhost) with cpus(*):4; mem(*):999; disk(*):55322; ports(*):[31000-32000] (allocated: )
master_1     | I0209 22:44:08.020138     8 master.cpp:4556] Sending updated checkpointed resources  to slave 3449ccad-9dee-4360-8360-c439ec66eafb-S0 at slave(1)@127.0.0.1:5051 (localhost)
slave_1      | I0209 22:44:08.020633    15 slave.cpp:1071] Re-registered with master master@127.0.0.1:5050
slave_1      | I0209 22:44:08.020716    15 slave.cpp:1107] Forwarding total oversubscribed resources 
slave_1      | I0209 22:44:08.021097    15 slave.cpp:2341] Updated checkpointed resources from  to 
slave_1      | I0209 22:44:08.021208    15 status_update_manager.cpp:181] Resuming sending status updates
master_1     | I0209 22:44:08.021109    10 master.cpp:4618] Received update of slave 3449ccad-9dee-4360-8360-c439ec66eafb-S0 at slave(1)@127.0.0.1:5051 (localhost) with total oversubscribed resources 
master_1     | I0209 22:44:08.021716    10 hierarchical.cpp:531] Slave 3449ccad-9dee-4360-8360-c439ec66eafb-S0 (localhost) updated with oversubscribed resources  (total: cpus(*):4; mem(*):999; disk(*):55322; ports(*):[31000-32000], allocated: )
slave_1      | I0209 22:44:56.605862    10 slave.cpp:4374] Current disk usage 42.53%. Max allowed age: 3.322600078987396days
```

Then when I try to hit the singularity UI here: http://localhost:7099/singularity the browser tells me that I'm unable to connect.

Eventually, the log immediately spews this:

```
...
scheduler_1       |     at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
scheduler_1       |     at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
scheduler_1       |     at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
scheduler_1       |     at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
scheduler_1       |     at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
scheduler_1       |     at com.google.inject.Guice.createInjector(Guice.java:96)
scheduler_1       |     at com.hubspot.dropwizard.guicier.GuiceBundle.run(GuiceBundle.java:104)
scheduler_1       |     at com.hubspot.dropwizard.guicier.GuiceBundle.run(GuiceBundle.java:56)
scheduler_1       |     at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:176)
scheduler_1       |     at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:41)
scheduler_1       |     at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76)
scheduler_1       |     at io.dropwizard.cli.Cli.run(Cli.java:70)
scheduler_1       |     at io.dropwizard.Application.run(Application.java:72)
scheduler_1       |     at com.hubspot.singularity.SingularityService.main(SingularityService.java:100)
scheduler_1       | Caused by: java.net.UnknownHostException: moby: moby: unknown error
scheduler_1       |     at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
scheduler_1       |     at com.hubspot.singularity.SingularityMainModule.getHostname(SingularityMainModule.java:188)
scheduler_1       |     ... 201 more
scheduler_1       | Caused by: java.net.UnknownHostException: moby: unknown error
scheduler_1       |     at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
scheduler_1       |     at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
scheduler_1       |     at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
scheduler_1       |     at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
scheduler_1       |     ... 202 more
scheduler_1       | 
scheduler_1       | 1054) Error in custom provider, java.lang.RuntimeException: No local hostname found, unable to start without functioning local networking (or configured hostname)
scheduler_1       |   at com.hubspot.singularity.SingularityMainModule.getHostname(SingularityMainModule.java:183) (via modules: com.hubspot.singularity.SingularityServiceModule -> com.hubspot.singularity.SingularityMainModule)
...
```

I had to interrupt docker as it was spewing the stack dump to the logs, apparently in an infinite loop.

I recreated this a couple of times, but now on my third try I still can't bring up the UI, but the logs are quiet. Just printing out:

```
slave_1      | I0209 22:44:56.605862    10 slave.cpp:4374] Current disk usage 42.53%. Max allowed age: 3.322600078987396days
slave_1      | I0209 22:45:56.607321    13 slave.cpp:4374] Current disk usage 42.53%. Max allowed age: 3.322600078987396days
slave_1      | I0209 22:46:56.607837    12 slave.cpp:4374] Current disk usage 42.53%. Max allowed age: 3.322599174206134days
slave_1      | I0209 22:47:56.608113     8 slave.cpp:4374] Current disk usage 42.53%. Max allowed age: 3.322599174206134days
slave_1      | I0209 22:48:56.609350    13 slave.cpp:4374] Current disk usage 42.53%. Max allowed age: 3.322599174206134days
slave_1      | I0209 22:49:56.610520    15 slave.cpp:4374] Current disk usage 42.53%. Max allowed age: 3.322599174206134days
slave_1      | I0209 22:50:56.610924    10 slave.cpp:4374] Current disk usage 42.53%. Max allowed age: 3.322599174206134days

```
I started it up again with baragon in there and once again I couldn't get a stack dump in the logs, but no UI either. docker-compose  doesn't show any ports:

```
biwrigh-mac:Singularity bill.w.wright$ docker-compose ps
            Name                          Command               State   Ports
-----------------------------------------------------------------------------
singularity_baragonagent_1     /usr/local/bin/supervisord ...   Up
singularity_baragonservice_1   /etc/baragon/start.sh            Up
singularity_master_1           mesos-master --registry=in ...   Up
singularity_scheduler_1        /etc/singularity/start.sh  ...   Up
singularity_slave_1            mesos-slave                      Up
singularity_zk_1               /run.sh                          Up
```
This was also in my logs:

```
master_1     | **************************************************
master_1     | Master bound to loopback interface! Cannot communicate with remote schedulers or slaves. You might want to set '--ip' flag to a routable IP address.
master_1     | **************************************************
lave_1      | **************************************************
slave_1      | Slave bound to loopback interface! Cannot communicate with remote master(s). You might want to set '--ip' flag to a routable IP address.
slave_1      | **************************************************
m
s
```

Does Singularity require Baragon?

Whenever I stop docker-compose (via a Ctrl-C), I get this one trackback:

```
Stopping singularity_master_1 ... 
Exception in thread Thread-9:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "compose/cli/log_printer.py", line 197, in watch_events
  File "compose/project.py", line 350, in events
  File "site-packages/docker/api/client.py", line 295, in _stream_helper
```

**Comment by ssalinas** [comment]
@billwright , this is the same issue as #1313. Right now the local dev setup relies on HOST network mode in docker, which unfortunately does not work when using docker for mac we found out. At the moment you'd have to use docker-machine
