### ISSUE TITLE
Unable to configure Google SMTP for email notifications

### ISSUE THREAD

**Issue by captify-iliesnov** [HubSpot/Singularity#1566]
Hi all!
We are trying to setup email notifications according to https://github.com/HubSpot/Singularity/blob/master/Docs/reference/configuration.md#smtp via Google SMTP.
For now notifications failing with errors (cleared personal info from logs).
**465 port:**
```java
javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 465, response: -1
WARN [2017-06-13 22:13:52,421] com.hubspot.singularity.smtp.SingularitySmtpSender: Unable to send message [to: [my_email_here@company_name.com], subject: Task finished (name_of_the_task_here)]
	at javax.mail.Service.connect(Service.java:386)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:697)
	at javax.mail.Service.connect(Service.java:245)
	at javax.mail.Transport.send0(Transport.java:253)
	at javax.mail.Service.connect(Service.java:194)
	at com.hubspot.singularity.smtp.SingularitySmtpSender.sendMail(SingularitySmtpSender.java:133)
	at com.hubspot.singularity.smtp.SingularitySmtpSender.lambda$queueMail$0(SingularitySmtpSender.java:81)
	at javax.mail.Transport.send(Transport.java:124)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
**587 port:**
```java
! com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.0 Must issue a STARTTLS command first. q48sm440530edd.65 - gsmtp
```
This might be related to https://github.com/HubSpot/Singularity/blob/master/SingularityService/src/main/java/com/hubspot/singularity/config/SMTPConfiguration.java#L48-L54
And no info on `ssl`/`startTLS` config in docs.

**Comment by ssalinas** [comment]
Does it work with `ssl`/`startTLS` set to `true`? We can update the docs to include those fields

**Comment by captify-iliesnov** [comment]
Additional information - Singularity version - `0.15.1`
No firewall enabled.
>Does it work with ssl/startTLS set to true? 
Nope

**Comment by captify-iliesnov** [comment]
We managed to resolve this issue (at least notifications work for us now).
Regarding question about `ssl/startTLS` in `singularity-config.yaml` - yes, both values were set to `true`, but this didn't help us.

The way issue was solved - added parameters `-Dmail.smtp.ssl.enable=true -Dmail.smtp.port=465` inside `start_singularity.sh` script (hello JavaMail docs).
*NB! This might require **`libmail-java`** to be installed (we are using Debian/Ubuntu)*

Full Singularity startup file:
```bash
# cat start_singularity.sh
#!/bin/bash
exec /usr/bin/java -Dmail.smtp.ssl.enable=true -Dmail.smtp.port=465 -Ddw.server.connector.port=${UI_PORT} -Ddw.mesos.master=${MESOS_MASTER} -Ddw.zookeeper.quorum=${ZK_QUORUM} -Ddw.ui.baseUrl=${BASE_URL} -Ddw.ui.title="${UI_TITLE}" -Ddw.hostname=${HOSTNAME} -jar SingularityService.jar server singularity-config.yaml
```
SMTP section of `singularity-config.yaml` (cleared personal info):
```yaml
smtp:
  username: *****@company_name.com
  password: *****
  host: smtp.gmail.com
  port: 465
  from: "singularity-qa@company_name.com"
  admins: ["my_email_here@company_name.com"]
  emails:
    TASK_LOST:
      - ADMINS
    TASK_FAILED:
      - ADMINS
    TASK_FAILED_DECOMISSIONED:
      - ADMINS
    TASK_KILLED:
      - ADMINS
    TASK_KILLED_DECOMISSIONED:
      - ADMINS
    TASK_KILLED_UNHEALTHY:
      - ADMINS
    TASK_SCHEDULED_OVERDUE_TO_FINISH:
      - ADMINS
    TASK_FINISHED_ON_DEMAND:
      - ADMINS
    TASK_FINISHED_RUN_ONCE:
      - ADMINS
    TASK_FINISHED_SCHEDULED:
      - ADMINS
    TASK_FINISHED_LONG_RUNNING:
      - ADMINS
```
Please update docs and/or code accordingly and feel free to close this issue.
