### ISSUE TITLE
Singularity behind proxy issue

### ISSUE THREAD

**Issue by petrovicboban** [HubSpot/Singularity#1723]
All of our singularity services are behind nginx proxy, with ssl certificate acl binded. Services are listening on localhost:7099, proxy is listening on publiv IPs, port 7100.    
I've updated one of three singularity services from 0.14.1 to 0.17.0.  When trying to deploy one test job using updated service, I've got error 500.  

```
TRACE [2018-02-20 15:55:22,382] com.hubspot.singularity.resources.AbstractLeaderAwareResource: Sending request to leader: http://db11.example.com:7099/singularity/api/deploys?user=boban   POST    headers:        Origin:https://db07.example.com:7100   Cookie:_ga=GA1.2.2007115827.1504283527; TWISTED_SESSION=f0d921132011378b60157ecc9cd72489        Accept:application/json X-Forwarded-Proto:https Connection:close        User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36    Referer:https://db07.example.com:7100/singularity/request/boban-test/deploy    Host:db07.example.com:7100     Accept-Encoding:gzip, deflate, br       X-Forwarded-For:24.135.20.205   Accept-Language:en-US,en;q=0.9,sr;q=0.8,hr;q=0.7,bs;q=0.6       Content-Length:443      X-Real-IP:24.135.20.205 Content-Type:application/json
ERROR [2018-02-20 15:55:22,386] com.hubspot.singularity.resources.AbstractLeaderAwareResource: Could not proxy request {} to leader
! java.net.ConnectException: Connection refused: db11.example.com/x.x.x.x:7099
! at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
! at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
! at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
! at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
! at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
! at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
! at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
! ... 3 common frames omitted
! Causing: java.net.ConnectException: Connection refused: db11.example.com/x.x.x.x:7099 to http://db11.example.com:7099/singularity/api/deploys?user=boban
! at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:103)
! ... 12 common frames omitted
! Causing: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: db11.example.com/x.x.x.x:7099 to http://db11.example.com:7099/singularity/api/deploys?user=boban
! at com.ning.http.client.providers.netty.NettyResponseFuture.abort(NettyResponseFuture.java:342)
! at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:107)
! at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
! at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:418)
! at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:380)
! at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109)
! at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
! at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
! at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
! at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
! at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
! at java.lang.Thread.run(Thread.java:748)
```

Obviously, service is trying to forward request to db11.example.com (current master), but to port 7099 using http scheme, probably discovered through zookeeper.

**Comment by ssalinas** [comment]
The Singularity instances will try to talk directly to each other, you are correct that this is discoveed via zookeeper. The host used is discovered via this method: https://github.com/HubSpot/Singularity/blob/master/SingularityService/src/main/java/com/hubspot/singularity/SingularityMainModule.java#L186-L201

It will attempt to find it's own IP to then broadcast to other hosts. If you need to override this due to the way routing is set up in your environment, you can set the `hostname` parameter in your yaml file to the dns or IP where that particular Singularity instance is reachable

**Comment by petrovicboban** [comment]
Does it allow scheme and port change?

**Comment by petrovicboban** [comment]
Right bellow that code is 
```
    private final String hostname;
    private final int httpPort;
```
Does that mean that https is not allowed?

**Comment by ssalinas** [comment]
The Singularity -> Singularity communication is all http right now, and is parsed from the dropwizard configuration. Given the nginx proxy setup you mentioned, it seems that nginx is terminating ssl already anyways

**Comment by petrovicboban** [comment]
I guess I will have to let Singularity bind to public ip (its on localhost now). I don't see other way.

**Comment by ssalinas** [comment]
Right now we don't have a port/scheme override, it's just grabbed form dropwizard configs. It's definitely something we can add in the future though.

**Comment by petrovicboban** [comment]
Thanks for help.
