### ISSUE TITLE
Fail to register in mesos

### ISSUE THREAD

**Issue by exponn** [HubSpot/Singularity#1959]
Hi,

After compiling the latest GIT version of Singularity, it is not able to register the Framework in Mesos. I attach the error that I have located:

```
INFO  [2019-06-18 15:43:25,762] com.hubspot.mesos.rx.java.MesosClient: Probing Mesos server at http://192.168.15.245:5050/redirect
INFO  [2019-06-18 15:43:26,870] com.hubspot.mesos.rx.java.MesosClient: Using new Mesos URI: http:/api/v1/scheduler
ERROR [2019-06-18 15:43:27,090] com.hubspot.singularity.mesos.SingularityMesosScheduler: uncaught exception
! java.lang.NullPointerException: value
! at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:31)
! at io.netty.handler.codec.DefaultHeaders.addObject(DefaultHeaders.java:327)
! at io.netty.handler.codec.http.DefaultHttpHeaders.add(DefaultHttpHeaders.java:117)
! at io.reactivex.netty.protocol.http.client.HttpRequestHeaders.add(HttpRequestHeaders.java:54)
! at io.reactivex.netty.protocol.http.client.HttpClientImpl.enrichRequest(HttpClientImpl.java:140)
! at io.reactivex.netty.protocol.http.client.HttpClientImpl.submit(HttpClientImpl.java:89)
! at io.reactivex.netty.protocol.http.client.HttpClientImpl.submit(HttpClientImpl.java:73)
! at io.reactivex.netty.protocol.http.client.HttpClientImpl.submit(HttpClientImpl.java:63)
! at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:231)
! at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:228)
! at rx.Observable.unsafeSubscribe(Observable.java:10327)
! at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
! at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
! at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
! at java.lang.Thread.run(Thread.java:748)
INFO  [2019-06-18 15:43:27,095] com.hubspot.singularity.mesos.SingularityMesosScheduler: Ignoring errorUncaughtException because scheduler isn't running (NOT_STARTED)
ERROR [2019-06-18 15:43:27,101] com.hubspot.singularity.mesos.SingularityMesosScheduler: uncaught exception
! java.lang.NullPointerException: value
! at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:31)
! at io.netty.handler.codec.DefaultHeaders.addObject(DefaultHeaders.java:327)
! at io.netty.handler.codec.http.DefaultHttpHeaders.add(DefaultHttpHeaders.java:117)
! at io.reactivex.netty.protocol.http.client.HttpRequestHeaders.add(HttpRequestHeaders.java:54)
! at io.reactivex.netty.protocol.http.client.HttpClientImpl.enrichRequest(HttpClientImpl.java:140)
! at io.reactivex.netty.protocol.http.client.HttpClientImpl.submit(HttpClientImpl.java:89)
! at io.reactivex.netty.protocol.http.client.HttpClientImpl.submit(HttpClientImpl.java:73)
! at io.reactivex.netty.protocol.http.client.HttpClientImpl.submit(HttpClientImpl.java:63)
! at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:231)
! at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:228)
! at rx.Observable.unsafeSubscribe(Observable.java:10327)
! at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
! at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
! at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
! at java.lang.Thread.run(Thread.java:748)
```

I have checked Mesos agents and they work correctly, and as an example the Marathon framework works without problems.

Thank you!

**Comment by ssalinas** [comment]
This should have been fixed in https://github.com/HubSpot/Singularity/pull/1954/commits/d00e6cad68fc7ebead2a75019f7b81628d8bb420 . What commit were you running?

**Comment by exponn** [comment]
Hello,

I'm in the master branch and the last commit is the "bc2399a".
Is it possible that some later commit cause this error?

Thank you!

**Comment by ssalinas** [comment]
That commit seems to be from a different branch. Can you get the newest master again and let us know if you still have the same issue?

**Comment by exponn** [comment]
Hi,
I have cloned the repository again to avoid any problem and it continues to fail. If I compile without omitting the tests, it gives the following error when it passes the tests for "SingularityUI":

**Failed to execute goal com.github.eirslett: frontend-maven-plugin: 0.0.23: npm (npm install) on project SingularityUI: Failed to run task: 'npm install --color = false' failed. (error code 1) -> [Help 1]**

**Comment by ssalinas** [comment]
Missed the `Using new Mesos URI: http:/api/v1/scheduler` in there at first. Seems that something in mesos-rxjava is causing [this](https://github.com/HubSpot/mesos-rxjava/blob/master/mesos-rxjava-client/src/main/java/com/hubspot/mesos/rx/java/MesosClient.java#L231) host and port to be null. What mesos master version are you running?

**Comment by exponn** [comment]
Hi,
I have cloned the repository again to avoid any problem and it continues to fail. If I compile without omitting the tests, it gives the following error when it passes the tests for "SingularityService":

**[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project SingularityService: There was a timeout or other error in the fork -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project SingularityService: There was a timeout or other error in the fork
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There was a timeout or other error in the fork
	at org.apache.maven.plugin.surefire.SurefireHelper.throwException(SurefireHelper.java:240)
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:112)
	at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:354)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1008)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:854)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more**

**Comment by ssalinas** [comment]
As a side note, is there a reason you do not use the official releases and jars published in maven?

**Comment by exponn** [comment]
> Missed the `Using new Mesos URI: http:/api/v1/scheduler` in there at first. Seems that something in mesos-rxjava is causing [this](https://github.com/HubSpot/mesos-rxjava/blob/master/mesos-rxjava-client/src/main/java/com/hubspot/mesos/rx/java/MesosClient.java#L231) host and port to be null. What mesos master version are you running?

I'm running Mesos version 1.8.0

**Comment by exponn** [comment]
I have reinstalled Maven to the latest version (3.6.0), erasing all the configuration and only applies the default configuration. I have tried compiling again and still giving error when compiling "SingularityService":

`
[INFO] Tests run: 25, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 168.662 s - in com.hubspot.singularity.scheduler.SingularityDeploysTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 197, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Singularity 0.23.0-SNAPSHOT:
[INFO] 
[INFO] Singularity ........................................ SUCCESS [ 32.864 s]
[INFO] SingularityBase .................................... SUCCESS [ 13.911 s]
[INFO] SingularityMesosClient ............................. SUCCESS [  3.353 s]
[INFO] SingularityUI ...................................... SUCCESS [02:37 min]
[INFO] SingularityService ................................. FAILURE [05:40 min]
[INFO] SingularityRunnerBase .............................. SKIPPED
[INFO] SingularityS3Base .................................. SKIPPED
[INFO] SingularityClient .................................. SKIPPED
[INFO] SingularityExecutor ................................ SKIPPED
[INFO] SingularityExecutorCleanup ......................... SKIPPED
[INFO] SingularityS3Uploader .............................. SKIPPED
[INFO] SingularityS3Downloader ............................ SKIPPED
[INFO] EmbedSingularityExample ............................ SKIPPED
[INFO] SingularityServiceIntegrationTests ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:09 min
[INFO] Finished at: 2019-06-20T19:03:44+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project SingularityService: There was a timeout or other error in the fork -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project SingularityService: There was a timeout or other error in the fork
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There was a timeout or other error in the fork
    at org.apache.maven.plugin.surefire.SurefireHelper.throwException (SurefireHelper.java:240)
    at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution (SurefireHelper.java:112)
    at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary (SurefirePlugin.java:354)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked (AbstractSurefireMojo.java:1008)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute (AbstractSurefireMojo.java:854)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
`

I guess the original problem may come from this point.

thanks

**Comment by exponn** [comment]
Hi,

Problem solved. The fault was in the resolution of the name of the machine.

When Singularity was looking for the host master of mesos (http://1.1.1.1:5050/redirect), this return the URL which the name of the machine (http://mesos.corp:5050) and for some reason Singularity could not resolve that name and then fail to boot.

If you configure the Mesos service with the parameter "--no-hostname_lookup", avoid this problem, but I think it should be analyzed because Singularity fails at this point when the name resolution works correctly.

Thanks

**Comment by ssalinas** [comment]
Singularity isn't using any special DNS settings. Are you able to resolve that same hostname from the machine that Singularity is running on? If not, there isn't much Singularity can do about it
