### ISSUE TITLE
Publish all artifacts to Maven Central

### ISSUE THREAD

**Issue by jloisel** [HubSpot/Singularity#391]
We're in the need of having the Singularity service shaded jar on Maven Central. This would allow us to launch Singularity without the need to build it. Bower is currently down, this prevents us from building Singularity and running our infrastructure. Pre-built Singularity would fix this. :)

It's more secure for us to rely on a stable version from Maven Central rather than build a snapshot from sources.

**Comment by tpetr** [comment]
@jloisel Singularity releases are always published to Maven Central: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.hubspot%22%20AND%20a%3A%22SingularityService%22

**Comment by jloisel** [comment]
Oh, thanks i haven't seen it on MvnRepo. :)

**Comment by tpetr** [comment]
no worries, feel free to reopen if you're seeing sync issues

**Comment by jloisel** [comment]
It seems like SingularityService Jar is lacking Main manifest attribute. There is no way to execute it.

When running it directly from command-line, using -Xdiag, i got:
java.lang.NoClassDefFoundError: io/dropwizard/Application
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
Caused by: java.lang.ClassNotFoundException: io.dropwizard.Application
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.load

I think that this jar is not the shaded one. Are you having issues building Singularity too on your side ? Our jenkins runs on EC2, and it gets stuck on:
"bower install --allow-root && brunch build --production"

Nothing happens, we execute simply "mvn package" on base pom.

**Comment by tpetr** [comment]
which jar are you using? since we moved to the basepom system, you should be using file that ends with `-shaded.jar` (on http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.hubspot%22%20AND%20a%3A%22SingularityService%22, it's the `shaded.jar` link)

i'm not seeing any issues with building bower / brunch locally. if you cd into `SingularityUI` and manually run `npm install`, do you get any more information about what's wrong?

**Comment by jloisel** [comment]
Damn, i'm asleep today!

I'm just getting those two lines output:
> SingularityUI@0.3.0 postinstall /home/jerome/git/Singularity/SingularityUI
> bower install --allow-root && brunch build --production

And stuck at this step. It was working fine for the past few months :)

**Comment by tpetr** [comment]
so it looks like npm installs fine, but it might not be relaying some of the output of bower / brunch. could you try running `bower install --allow-root && brunch build --production` in the SingularityUI folder and see if anything different happens?

**Comment by Eseb** [comment]
@jloisel I tried building it myself and it stopped progressing during the Brunch build for no reason. It fixed itself after removing all the deps then re-downloading them and trying to build again. Try that and see if it fixes itself.

```
rm -rf bower_components node_modules
npm install
```

**Comment by jloisel** [comment]
Thanks for your help guys :+1: 

I changed my build to use the shaded jar instead of building from sources. There is a small UI glitch in 0.4.0 but it's okay (popups are displayed at the bottom of the page).
