### ISSUE TITLE
(logfetch) re-download and/or ignore files that fail CRC check

### ISSUE THREAD

**Issue by tpetr** [HubSpot/Singularity#392]
logfetch seemed to download a corrupted log file:

```
Thomass-MacBook-Pro:~ tpetr$ logfetch -r NavigationService-web -g 99109243
Checking for S3 log files
finished downloading /Users/tpetr/.logfetch_cache/NavigationService-web-5157_134_47-1420924750714-4-crisawn-us_east_1b_0-1421033374000.gz
finished downloading /Users/tpetr/.logfetch_cache/NavigationService-web-5157_134_47-1420924750683-3-kolloen-us_east_1a_0-1421032835000.gz
finished downloading /Users/tpetr/.logfetch_cache/NavigationService-web-5157_134_47-1420924750616-1-thoroughfare-us_east_1e_0-1421032747000.gz
finished downloading /Users/tpetr/.logfetch_cache/NavigationService-web-5157_134_47-1420924750649-2-kissacook-us_east_1e_0-1421034429000.gz
Unpacked /Users/tpetr/.logfetch_cache/NavigationService-web-5125_108_20-1415387772620-1-scareast-us_east_1b_0-1415388946000.gz
Unpacked /Users/tpetr/.logfetch_cache/NavigationService-web-5125_108_20-1415387774620-2-corbinhorsestamp-us_east_1e_0-1415388946000.gz
Unpacked /Users/tpetr/.logfetch_cache/NavigationService-web-5125_108_20-1415387774638-3-horus-us_east_1e_0-1415388946000.gz
Unpacked /Users/tpetr/.logfetch_cache/NavigationService-web-5125_108_20-1415387774659-4-pungo-us_east_1b_0-1415388945000.gz
Unpacked /Users/tpetr/.logfetch_cache/NavigationService-web-5125_109_21-1415388915803-1-trainor-us_east_1e_0-1415502724000.gz
Unpacked /Users/tpetr/.logfetch_cache/NavigationService-web-5125_109_21-1415388915803-1-trainor-us_east_1e_0-1415589903000.gz
...snip...
Unpacked /Users/tpetr/.logfetch_cache/NavigationService-web-5132_112_24-1415818678516-4-floprock-us_east_1e_0-1416413465000.gz
Traceback (most recent call last):
  File "/Users/tpetr/.singularity-logfetch_virtualenv/bin/logfetch", line 8, in <module>
    load_entry_point('singularity-logfetch==0.0.5', 'console_scripts', 'logfetch')()
  File "/Users/tpetr/.singularity-logfetch_virtualenv/lib/python2.7/site-packages/logfetch/entrypoint.py", line 88, in fetch
    fetch_logs(args)
  File "/Users/tpetr/.singularity-logfetch_virtualenv/lib/python2.7/site-packages/logfetch/entrypoint.py", line 32, in fetch_logs
    all_logs += download_s3_logs(args)
  File "/Users/tpetr/.singularity-logfetch_virtualenv/lib/python2.7/site-packages/logfetch/s3_logs.py", line 36, in download_s3_logs
    logfetch_base.unpack_logs(zipped_files)
  File "/Users/tpetr/.singularity-logfetch_virtualenv/lib/python2.7/site-packages/logfetch/logfetch_base.py", line 18, in unpack_logs
    file_out.write(file_in.read())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 254, in read
    self._read(readsize)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 308, in _read
    self._read_eof()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 347, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0xb17a66b0 != 0x1d70c6caL
```

I can't seem to get past this without manually clearing out the logfetch cache

**Comment by ssalinas** [comment]
This is fixed
