### ISSUE TITLE
Failed to parse cgroup information

### ISSUE THREAD

**Issue by gtinjr** [HubSpot/Singularity#741]
I am trying to get singularity executor working on a mesos slave node.  Whenever I try to run a task using the signularity executor it fails to read the cgroup information.  The /prod/{PID}/cgroup directory exist but it contains no data.
I am running singularity executor 0.4.5 on  Ubuntu 12.04(Precise) and kernel 3.2.0-67-virtual on a amazon EC2 instance.

java.lang.RuntimeException: Unable to parse cgroup container from /proc/25758/cgroup
	at com.hubspot.singularity.executor.SingularityExecutorThreadChecker.getNumUsedThreads(SingularityExecutorThreadChecker.java:131) [SingularityExecutor-0.4.5-shaded.jar:0.4.5]
	at com.hubspot.singularity.executor.SingularityExecutorThreadChecker.checkThreads(SingularityExecutorThreadChecker.java:86) [SingularityExecutor-0.4.5-shaded.jar:0.4.5]
	at com.hubspot.singularity.executor.SingularityExecutorThreadChecker.access$000(SingularityExecutorThreadChecker.java:32) [SingularityExecutor-0.4.5-shaded.jar:0.4.5]
	at com.hubspot.singularity.executor.SingularityExecutorThreadChecker$1.run(SingularityExecutorThreadChecker.java:65) [SingularityExecutor-0.4.5-shaded.jar:0.4.5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_07]
	at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351) [na:1.7.0_07]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178) [na:1.7.0_07]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_07]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_07]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [na:1.7.0_07]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [na:1.7.0_07]
	at java.lang.Thread.run(Thread.java:722) [na:1.7.0_07]

**Comment by ssalinas** [comment]
This error can often occur when only posix isolation is being used and not cgroup isolation. I have made changes in #959 so that you can configure the type of thread checking (cgroup or pstree) as well as configurably fall back to pstree when cgroup fails.
