### ISSUE TITLE
zookeeper_init failed: Invalid argument

### ISSUE THREAD

**Issue by scalp42** [HubSpot/Singularity#769]
Using Singularity v0.4.5, I'm running this issue:

```
2015-11-20 01:35:33,030:17903(0x7f5d78183700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2015-11-20 01:35:33,030:17903(0x7f5d78183700):ZOO_INFO@log_env@716: Client environment:host.name=mesos1
2015-11-20 01:35:33,030:17903(0x7f5d78183700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
2015-11-20 01:35:33,030:17903(0x7f5d78183700):ZOO_INFO@log_env@724: Client environment:os.arch=3.19.0-33-generic
2015-11-20 01:35:33,030:17903(0x7f5d78183700):ZOO_INFO@log_env@725: Client environment:os.version=#38~14.04.1-Ubuntu SMP Fri Nov 6 18:17:28 UTC 2015
2015-11-20 01:35:33,030:17903(0x7f5d78183700):ZOO_INFO@log_env@733: Client environment:user.name=ubuntu
2015-11-20 01:35:33,030:17903(0x7f5d78183700):ZOO_INFO@log_env@741: Client environment:user.home=/root
2015-11-20 01:35:33,030:17903(0x7f5d78183700):ZOO_INFO@log_env@753: Client environment:user.dir=/root
2015-11-20 01:35:33,030:17903(0x7f5d78183700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=10.42.122.245 sessionTimeout=10000 watcher=0x7f5d8dc46600 sessionId=0 sessionPasswd=<null> context=0x7f5d9800c3d0 flags=0
2015-11-20 01:35:33,030:17903(0x7f5d78183700):ZOO_ERROR@getaddrs@489: no port in 10.42.122.245
W1120 01:35:33.030890 18033 zookeeper.cpp:101] zookeeper_init failed: Invalid argument ; retrying in 1 second
2015-11-20 01:35:34,031:17903(0x7f5d78183700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2015-11-20 01:35:34,031:17903(0x7f5d78183700):ZOO_INFO@log_env@716: Client environment:host.name=mesos1
2015-11-20 01:35:34,031:17903(0x7f5d78183700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
2015-11-20 01:35:34,031:17903(0x7f5d78183700):ZOO_INFO@log_env@724: Client environment:os.arch=3.19.0-33-generic
2015-11-20 01:35:34,031:17903(0x7f5d78183700):ZOO_INFO@log_env@725: Client environment:os.version=#38~14.04.1-Ubuntu SMP Fri Nov 6 18:17:28 UTC 2015
2015-11-20 01:35:34,031:17903(0x7f5d78183700):ZOO_INFO@log_env@733: Client environment:user.name=ubuntu
2015-11-20 01:35:34,031:17903(0x7f5d78183700):ZOO_INFO@log_env@741: Client environment:user.home=/root
2015-11-20 01:35:34,031:17903(0x7f5d78183700):ZOO_INFO@log_env@753: Client environment:user.dir=/root
2015-11-20 01:35:34,031:17903(0x7f5d78183700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=10.42.122.245 sessionTimeout=10000 watcher=0x7f5d8dc46600 sessionId=0 sessionPasswd=<null> context=0x7f5d9800c3d0 flags=0
2015-11-20 01:35:34,031:17903(0x7f5d78183700):ZOO_ERROR@getaddrs@489: no port in 10.42.122.245
W1120 01:35:34.031913 18033 zookeeper.cpp:101] zookeeper_init failed: Invalid argument ; retrying in 1 second
2015-11-20 01:35:35,032:17903(0x7f5d78183700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2015-11-20 01:35:35,032:17903(0x7f5d78183700):ZOO_INFO@log_env@716: Client environment:host.name=mesos1
2015-11-20 01:35:35,032:17903(0x7f5d78183700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
2015-11-20 01:35:35,032:17903(0x7f5d78183700):ZOO_INFO@log_env@724: Client environment:os.arch=3.19.0-33-generic
2015-11-20 01:35:35,032:17903(0x7f5d78183700):ZOO_INFO@log_env@725: Client environment:os.version=#38~14.04.1-Ubuntu SMP Fri Nov 6 18:17:28 UTC 2015
2015-11-20 01:35:35,032:17903(0x7f5d78183700):ZOO_INFO@log_env@733: Client environment:user.name=ubuntu
2015-11-20 01:35:35,032:17903(0x7f5d78183700):ZOO_INFO@log_env@741: Client environment:user.home=/root
2015-11-20 01:35:35,032:17903(0x7f5d78183700):ZOO_INFO@log_env@753: Client environment:user.dir=/root
2015-11-20 01:35:35,032:17903(0x7f5d78183700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=10.42.122.245 sessionTimeout=10000 watcher=0x7f5d8dc46600 sessionId=0 sessionPasswd=<null> context=0x7f5d9800c3d0 flags=0
2015-11-20 01:35:35,032:17903(0x7f5d78183700):ZOO_ERROR@getaddrs@489: no port in 10.42.122.245
W1120 01:35:35.032279 18033 zookeeper.cpp:101] zookeeper_init failed: Invalid argument ; retrying in 1 second
^CINFO  [2015-11-20 01:35:35,813] org.eclipse.jetty.server.ServerConnector: Stopped SingularityService@f4cfd90{HTTP/1.1}{0.0.0.0:8070}
INFO  [2015-11-20 01:35:35,814] org.eclipse.jetty.server.handler.ContextHandler: Stopped i.d.j.MutableServletContextHandler@35267fd4{/admin,null,UNAVAILABLE}
INFO  [2015-11-20 01:35:35,814] org.eclipse.jetty.server.handler.ContextHandler: Stopped i.d.j.MutableServletContextHandler@3ad4a7d6{/singularity,null,UNAVAILABLE}
I1120 01:35:35.832783 18189 sched.cpp:1805] Asked to abort the driver
I1120 01:35:35.857381 18028 sched.cpp:1070] Aborting framework 'Singularity'
```

This line is the culprit: 

```
2015-11-20 01:35:33,030:17903(0x7f5d78183700):ZOO_ERROR@getaddrs@489: no port in 10.42.122.245
W1120 01:35:33.030890 18033 zookeeper.cpp:101] zookeeper_init failed: Invalid argument ; retrying in 1 second
```

I can connect to that Zk instance perfectly fine (and actually see `/singularity` in it):

```
root@mesos1# nc -v -z -w1 10.42.122.245 2181
Connection to 10.42.122.245 2181 port [tcp/*] succeeded!
```

Here is my config file:

```yaml
# Run SingularityService on port 7099 and log to /var/log/singularity-access.log
server:
  type: simple
  applicationContextPath: /singularity
  connector:
    type: http
    port: 8070
  requestLog:
    appenders:
      - type: file
        currentLogFilename: /var/log/singularity-access.log
        archivedLogFilenamePattern: /var/log/singularity-access-%d.log.gz

mesos:
  master: zk://10.42.122.245/mesos
  defaultCpus: 1
  defaultMemory: 128
  frameworkName: Singularity
  frameworkId: Singularity
  frameworkFailoverTimeout: 1000000

zookeeper:
  quorum: 10.42.122.245:2181
  zkNamespace: singularity
  sessionTimeoutMillis: 60000
  connectTimeoutMillis: 5000
  retryBaseSleepTimeMilliseconds: 1000
  retryMaxTries: 3

logging:
  loggers:
    "com.hubspot.singularity" : TRACE

enableCorsFilter: true
sandboxDefaultsToTaskId: false  # enable if using SingularityExecutor

ui:
  title: Singularity
  baseUrl: http://xx.xx.xx.us-west-2.compute.amazonaws.com:8070/singularity

hostname: xx.xx.xx.us-west-2.compute.amazonaws.com
```

I've tried the following formats in case but no dice:

```
zk://10.42.122.245 2181
10.42.122.245
10.42.122.245:2181
```

Thanks for looking at it!

**Comment by tpetr** [comment]
@scalp42 from your examples it doesn't look like you've given `zk://10.42.122.245:2181/mesos` a try yet (which is the format that we're using in our own configs at HubSpot) -- could you test that and let us know?

**Comment by scalp42** [comment]
@tpetr no dice, using the same format as `mesos.master` key (it crashes directly):

```
INFO  [2015-11-20 18:43:18,921] org.apache.zookeeper.ZooKeeper: Initiating client connection, connectString=zk://10.42.122.245:2181/mesos sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@4dbad37
ERROR [2015-11-20 18:43:18,925] org.apache.curator.framework.imps.CuratorFrameworkImpl: Background exception was not retry-able or retry gave up
! java.lang.IllegalArgumentException: Invalid path string "//10.42.122.245:2181/mesos" caused by empty node name specified @1
! at org.apache.zookeeper.common.PathUtils.validatePath(PathUtils.java:99) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.apache.zookeeper.client.ConnectStringParser.<init>(ConnectStringParser.java:57) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:443) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.apache.curator.utils.DefaultZookeeperFactory.newZooKeeper(DefaultZookeeperFactory.java:29) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.apache.curator.framework.imps.CuratorFrameworkImpl$2.newZooKeeper(CuratorFrameworkImpl.java:146) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.apache.curator.HandleHolder$1.getZooKeeper(HandleHolder.java:94) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.apache.curator.HandleHolder.getZooKeeper(HandleHolder.java:55) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.apache.curator.ConnectionState.reset(ConnectionState.java:218) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.apache.curator.ConnectionState.start(ConnectionState.java:102) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.apache.curator.CuratorZookeeperClient.start(CuratorZookeeperClient.java:189) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.apache.curator.framework.imps.CuratorFrameworkImpl.start(CuratorFrameworkImpl.java:248) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at com.hubspot.singularity.SingularityCuratorProvider.start(SingularityCuratorProvider.java:56) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.server.Server.start(Server.java:342) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.server.Server.doStart(Server.java:290) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.Application.run(Application.java:72) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at com.hubspot.singularity.SingularityService.main(SingularityService.java:102) [SingularityService-0.4.5-shaded.jar:0.4.5]
WARN  [2015-11-20 18:43:23,927] org.eclipse.jetty.util.component.AbstractLifeCycle: FAILED com.hubspot.singularity.SingularityCuratorProvider@12958360: java.lang.IllegalStateException: did not connect to zookeeper
! java.lang.IllegalStateException: did not connect to zookeeper
! at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at com.hubspot.singularity.SingularityCuratorProvider.start(SingularityCuratorProvider.java:61) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.server.Server.start(Server.java:342) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.server.Server.doStart(Server.java:290) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.Application.run(Application.java:72) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at com.hubspot.singularity.SingularityService.main(SingularityService.java:102) [SingularityService-0.4.5-shaded.jar:0.4.5]
WARN  [2015-11-20 18:43:23,927] org.eclipse.jetty.util.component.AbstractLifeCycle: FAILED org.eclipse.jetty.server.Server@67110f71: java.lang.IllegalStateException: did not connect to zookeeper
! java.lang.IllegalStateException: did not connect to zookeeper
! at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at com.hubspot.singularity.SingularityCuratorProvider.start(SingularityCuratorProvider.java:61) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.server.Server.start(Server.java:342) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.server.Server.doStart(Server.java:290) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.Application.run(Application.java:72) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at com.hubspot.singularity.SingularityService.main(SingularityService.java:102) [SingularityService-0.4.5-shaded.jar:0.4.5]
ERROR [2015-11-20 18:43:23,928] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! java.lang.IllegalStateException: did not connect to zookeeper
! at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at com.hubspot.singularity.SingularityCuratorProvider.start(SingularityCuratorProvider.java:61) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.server.Server.start(Server.java:342) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.server.Server.doStart(Server.java:290) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43) ~[SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at io.dropwizard.Application.run(Application.java:72) [SingularityService-0.4.5-shaded.jar:0.4.5]
! at com.hubspot.singularity.SingularityService.main(SingularityService.java:102) [SingularityService-0.4.5-shaded.jar:0.4.5]
java.lang.IllegalStateException: did not connect to zookeeper
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at com.hubspot.singularity.SingularityCuratorProvider.start(SingularityCuratorProvider.java:61)
	at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118)
	at org.eclipse.jetty.server.Server.start(Server.java:342)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60)
	at org.eclipse.jetty.server.Server.doStart(Server.java:290)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76)
	at io.dropwizard.cli.Cli.run(Cli.java:70)
	at io.dropwizard.Application.run(Application.java:72)
	at com.hubspot.singularity.SingularityService.main(SingularityService.java:102)
```

**Comment by scalp42** [comment]
Worth mentioning that I tried to follow https://github.com/HubSpot/Singularity/blob/master/Docs/install.md#5-create-singularity-config-file

**Comment by scalp42** [comment]
PEBKAC: Answered on Slack, was not formatting `mesos.master` correctly:

```
zk://10.42.122.245/mesos

vs

zk://10.42.122.245:2181/mesos
```
